# reference
#  https://github.com/fchollet/keras/blob/master/.travis.yml
sudo: required
dist: trusty
language: python
python:
  - "3.5"
# command to install dependencies
install:
  - pip install numpy
  - pip install tf-nightly
script:
  - pytest
